-- hyprland.lua
-- Generated by hypr-migrate from: hyprland.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       5 resolved
--   Config keys:     40 emitted
--   Monitors:        3
--   Keybinds:        42 total, 17 collapsed into loops
--   Window rules:    0 total, 0 merged
--   Workspace rules: 0
--   Exec commands:   4
--   Gestures:        1
--   Warnings:        10  ← search MIGRATION_WARNING
--   Review needed:   1  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun"
local Browser = "vivaldi"
local mainMod = "SUPER"

hl.env("__GL_GSYNC_ALLOWED", "1")
hl.env("__GL_VRR_ALLOWED", "0")

hl.config({
    general = {
        allow_tearing = false,
        border_size = 0,
        col.active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
        col.inactive_border = "rgba(595959aa)",
        gaps_in = 5,
        gaps_out = 5,
        layout = "master",
        resize_on_border = false,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = true,
            passes = 1,
            size = 3,
            vibrancy = 0.1696,
        },
        inactive_opacity = 1.0,
        rounding = 2,
        rounding_power = 2,
        shadow = {
            color = "rgba(1a1a1aee)",
            enabled = true,
            range = 4,
            render_power = 3,
        },
    },
    input = {
        follow_mouse = 1,
        kb_layout = "us",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        kb_variant = "",
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
    misc = {
        disable_hyprland_logo = false,
        force_default_wallpaper = -1,
    },
    master = {
        new_status = "master",
    },
    animations = {
        enabled = "yes, please :)",
    },
    -- MIGRATION_WARNING: Conflicting value for .bindel: ',XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-' (line 308) vs ',XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+' (line 303)
    bindel = ",XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-",
    device = {
        name = "epic-mouse-v1",
        sensitivity = -0.5,
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

hl.monitor({ output = "DP-1", position = "0x0" })
hl.monitor({ output = "DP-1", mode = "1920x1080", refresh = 165, position = "0x0" })
hl.monitor({ output = "HDMI-A-1", mode = "1360x768w@60.00", position = "auto" })

hl.bind("SUPER + Return", function()
    hl.exec_cmd("kitty")
end)
hl.bind("SUPER + Q", hl.dsp.killactive())
-- MIGRATION_NOTE: hl.dsp.exit() is not available in Lua; use uwsm stop instead (see wiki)
-- MIGRATION_NOTE: hl.dsp.exit() is not available; use uwsm stop instead
-- was: bind = SUPER, X, exit, 
hl.bind("SUPER + E", function()
    hl.exec_cmd("thunar")
end)
hl.bind("SUPER + F", hl.dsp.fullscreen({ 0 }))
hl.bind("SUPER + B", function()
    hl.exec_cmd("vivaldi")
end)
hl.bind("SUPER + V", function()
    hl.exec_cmd("rofi -show drun")
end)
hl.bind("SUPER + P", hl.dsp.pseudo())
hl.bind("SUPER + left", hl.dsp.movefocus({ l }))
hl.bind("SUPER + right", hl.dsp.movefocus({ r }))
hl.bind("SUPER + up", hl.dsp.movefocus({ u }))
hl.bind("SUPER + down", hl.dsp.movefocus({ d }))
-- PATTERN: 9 sequential binds collapsed to loop
for i = 1, 9 do
    hl.bind("SUPER + " .. (i % 10), hl.dsp.focus({ workspace = tostring(i % 10) }))
end

-- PATTERN: 10 sequential binds collapsed to loop
for i = 1, 10 do
    hl.bind("SUPER SHIFT + " .. (i % 10), hl.dsp.focus({ workspace = tostring(i % 10) }))
end

hl.bind("SUPER + S", hl.dsp.togglespecialworkspace({ magic }))
hl.bind("SUPER SHIFT + S", hl.dsp.focus({ workspace = "special:magic" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.movewindow()), { mouse = true }
hl.bind("SUPER + mouse:273", hl.dsp.resizewindow()), { mouse = true }
hl.bind(" + XF86AudioNext", function()
    hl.exec_cmd("playerctl next")
end), { locked = true }
hl.bind(" + XF86AudioPause", function()
    hl.exec_cmd("playerctl play-pause")
end), { locked = true }
hl.bind(" + XF86AudioPlay", function()
    hl.exec_cmd("playerctl play-pause")
end), { locked = true }
hl.bind(" + XF86AudioPrev", function()
    hl.exec_cmd("playerctl previous")
end), { locked = true }
hl.bind(" + Print", function()
    hl.exec_cmd("flameshot gui")
end)

hl.on("hyprland.start", function()
    hl.exec_cmd("quickshell &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("dunst &")
    hl.exec_cmd("lxsession &")
end)

hl.curve("easeOutQuint", {
    type = "bezier",
    points = { {0.23, 1.0}, {0.32, 1.0} }
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { {0.65, 0.05}, {0.36, 1.0} }
})
hl.curve("linear", {
    type = "bezier",
    points = { {0.0, 0.0}, {1.0, 1.0} }
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { {0.5, 0.5}, {0.75, 1.0} }
})
hl.curve("quick", {
    type = "bezier",
    points = { {0.15, 0.0}, {0.1, 1.0} }
})

hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10.0,
    curve = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    curve = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    curve = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    curve = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    curve = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    curve = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    curve = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    curve = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    curve = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4.0,
    curve = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    curve = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    curve = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    curve = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    curve = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    curve = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    curve = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7.0,
    curve = "quick",
})
